# Generated by Django 5.0.3 on 2024-03-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
