# Generated by Django 5.0.3 on 2024-03-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
    ]
