# Generated by Django 5.0.3 on 2024-03-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_options_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
