# Generated by Django 5.0.3 on 2024-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_author_alter_book_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='history',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
