# Generated by Django 5.0.3 on 2024-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_genre_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reveiw',
        ),
    ]
