# Generated by Django 5.0.3 on 2024-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(null=True, upload_to='coverpages/'),
        ),
    ]
