# Generated by Django 5.0.3 on 2024-03-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_cover_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_page',
            new_name='coverpage',
        ),
    ]
