# Generated by Django 5.0.3 on 2024-03-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_history_book_borrowed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrowed_by',
            new_name='history',
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
