# Generated by Django 5.0.3 on 2024-03-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_history_book_borrowed_by_and_more'),
        ('user', '0012_alter_borrowedbook_book_alter_shelf_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='shelves', to='core.book'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='core.book'),
        ),
    ]
