# Generated by Django 5.0.3 on 2024-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_cover_page_book_coverpage'),
        ('user', '0012_alter_shelf_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='core.book'),
        ),
    ]
