# Generated by Django 5.0.3 on 2024-03-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_borrowedbook_book_alter_shelf_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='book',
            new_name='books',
        ),
    ]
