# Generated by Django 5.0.3 on 2024-03-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_review_book_alter_review_user'),
        ('user', '0014_alter_borrowedbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
