# Generated by Django 5.0.3 on 2024-03-17 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_history_book_borrowed_by_and_more'),
        ('user', '0014_rename_book_borrowedbook_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='books',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='core.book'),
        ),
    ]
