# Generated by Django 5.0.3 on 2024-03-16 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_review_book_alter_review_user'),
        ('user', '0015_alter_borrowedbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='borrowedbooks', to='core.book'),
        ),
    ]
