# Generated by Django 5.0.3 on 2024-03-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_history_book_borrowed_by_and_more'),
        ('user', '0015_remove_borrowedbook_books_alter_borrowedbook_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='books',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='book',
            field=models.ManyToManyField(blank=True, to='core.book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='shelves', to='core.book'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='core.book'),
        ),
    ]
