# Generated by Django 5.0.3 on 2024-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_review_book_alter_review_user'),
        ('user', '0016_remove_borrowedbook_book_alter_borrowedbook_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ManyToManyField(blank=True, to='core.book'),
        ),
    ]
